language: java
jdk:
- oraclejdk7
env:
  global:
  - secure: DvVG3sBG0DEwp030FZC/IVxBU8KABt1UUR490Br7bzhb+Mgx3HUXtkA35NYGfuYUGxd+yQFXoeQpAUNdaKO10cfEdos4N8ahBo+3ALSu9RESz48bztYHAali8Ob13Vgy4rgGbXQZJEAJJ144iwmTpCSspdRGFbdnSPzQlnDyNEw=
  - secure: V2R9KHLytC6I4tPfZzTvAzeD+HSt07TePG39Z3UKzRe+fqV/eeu7aOowKQyfdy1S/q4e4d/tFCQD74+p02upTgO9VD8HCp0YEaw2/2Yfrf33wIy5d5TXFrcZsEJI17c7UroiqCXW1ZvWz2XpGEss/yXlaUiAzFzoUYCbCy75hig=
  - secure: Zk9Xr1pPZFuYmVO8kjDqRojF5AVeXNThRtKfA9pbEhjfPla1eP4+1ZdvSF6GGdPydFdXKKyeSDU0IPxlEFBoyiyofOOc1X4pdnmDUuaYpltPvqJ8QnXeAKW5+TK31c5t6B+tSPS+rLmRmerpWBEYsOmCRh96dHK3r5VMP+JMQi4=
  - secure: pLeGQPFM1/VtXS2yPlQMZ6utoOT9HwJUCXsr2OQmlo2ib3HAIQsbw2zOiwIoIDXGk6UxQnDBky8YIJSzVYzunNG8TWqJMToCwhympGfyboT5xguGGw+UD9zmM56zeJ4lC40njI/F4s5OScSWAMNbqWGz7zj2+CrXWIpNM1JgpvA=
  - secure: k/SV4WZ+CgGNgdpS8COa+9x/jrQ174nnyurSLop8vV6d5WJoX44+es+UhuAZhStrsKLNW7OKrfaEEJZqM6wA8qfSN0OlTKXIP9WZPsdCyfZ5DZe7nIEi/WbeCw1SAXNE+JorHzZHtfegVp+UuAWYV0sjdhjKAem0rNxGinYiiwc=
  - secure: fUHnTyIf1aPIfHdgV44f57DhElXHEEdJvdfarLC4YyrQufNGWjDqnHsUV+NHJQuSvLJktzYo0QPTTs0332NnlekDH/WKTG6ZLmS5Z9Ks/MxiypotXwi5JnvPseIix75UVmtj+MoMTdRilzmWWF+Kmv7AnqNmvtWqMw9ft4g4Bwk=
after_success:
- mvn clean test jacoco:report coveralls:report deploy --settings travis-settings.xml
